name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java: [ '8', '11' ]

    name: Java ${{ matrix.java }} build
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-java@v4
      with:
        java-version: ${{ matrix.java }}
        distribution: 'temurin'
    - name: Build Java ${{ matrix.java }}
      uses: gradle/actions/setup-gradle@v3
      if: matrix.java != 11
      with:
        arguments: test
    - name: Build Java 11
      uses: gradle/actions/setup-gradle@v3
      if: matrix.java == 11
      with:
        arguments: jacocoTestReport coveralls
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
    
